### ISSUE TITLE
Hide player hands when in the orders hidden area

### ISSUE THREAD

**Issue by emberborja** [emberborja/ForbiddenStarsMod#12]
it is possible to discern what a player will choose by watching their hand in the order area. It is possible to hide the hand within the game when it is in this area.

**Comment by Oh-no-found-a-bug** [comment]
Alternative: Randomize the placement of the hidden orders at the start of the game. When players drag back their orders into their hidden zone, they can make sure to drop them in different locations every time.

**Comment by emberborja** [comment]
https://youtu.be/DqVCW-aJSsE?t=229

**Comment by emberborja** [comment]
I figured out how to make the change, but I don't see how to do it through the code unfortunately. It is possible to add this to the mod by going into TTS and selecting the zone tool (F3) => 

![Image](https://github.com/emberborja/ForbiddenStarsMod/assets/38664600/dfca7ab6-52e8-4d67-9e25-041469e9b983)

By right clicking the zones with the zone tool, you should get a context menu that shows a "hide pointers" checkbox. => 

![Image](https://github.com/emberborja/ForbiddenStarsMod/assets/38664600/202ee7a3-44cf-4d19-8371-6df2a5a2a9ee)


By clicking that checkbox on all four zones, we should be able to update the mod and this will be set by default when anyone uses the mod.

**Comment by emberborja** [comment]
Fugl implemented the change and tested it. This is resolved
